volumes:
  mysql_data:
services:
  gemini-balance:
    build: .
    container_name: gemini-balance
    restart: unless-stopped
    ports:
      - "10000:8000"
    environment:
      - ALLOWED_TOKENS=${ALLOWED_TOKENS:-[]}
      - API_KEYS=${API_KEYS:-[]}
      - AUTH_TOKEN=${AUTH_TOKEN:-}
      - DATABASE_TYPE=${DATABASE_TYPE:-mysql}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - BASE_URL=${BASE_URL:-https://generativelanguage.googleapis.com/v1beta}
      - MAX_FAILURES=${MAX_FAILURES:-10}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - TEST_MODEL=${TEST_MODEL:-gemini-1.5-flash}
      - TIME_OUT=${TIME_OUT:-300}
      - PROXIES=${PROXIES:-[]}
      - VERTEX_API_KEYS=${VERTEX_API_KEYS:-[]}
      - SEARCH_MODELS=${SEARCH_MODELS:-["gemini-2.0-flash-exp"]}
      - IMAGE_MODELS=${IMAGE_MODELS:-["gemini-2.0-flash-exp"]}
      - FILTERED_MODELS=${FILTERED_MODELS:-[]}
      - TOOLS_CODE_EXECUTION_ENABLED=${TOOLS_CODE_EXECUTION_ENABLED:-false}
      - SHOW_SEARCH_LINK=${SHOW_SEARCH_LINK:-true}
      - SHOW_THINKING_PROCESS=${SHOW_THINKING_PROCESS:-true}
      - THINKING_MODELS=${THINKING_MODELS:-[]}
      - THINKING_BUDGET_MAP=${THINKING_BUDGET_MAP:-{}}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - AUTO_DELETE_ERROR_LOGS_ENABLED=${AUTO_DELETE_ERROR_LOGS_ENABLED:-true}
      - AUTO_DELETE_ERROR_LOGS_DAYS=${AUTO_DELETE_ERROR_LOGS_DAYS:-7}
      - AUTO_DELETE_REQUEST_LOGS_ENABLED=${AUTO_DELETE_REQUEST_LOGS_ENABLED:-false}
      - AUTO_DELETE_REQUEST_LOGS_DAYS=${AUTO_DELETE_REQUEST_LOGS_DAYS:-30}
      - SAFETY_SETTINGS=${SAFETY_SETTINGS:-[]}
      - CHECK_INTERVAL_HOURS=${CHECK_INTERVAL_HOURS:-1}
      - TIMEZONE=${TIMEZONE:-Asia/Shanghai}
      - FAKE_STREAM_ENABLED=${FAKE_STREAM_ENABLED:-false}
      - FAKE_STREAM_EMPTY_DATA_INTERVAL_SECONDS=${FAKE_STREAM_EMPTY_DATA_INTERVAL_SECONDS:-5}
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; exit(0) if requests.get('http://localhost:8000/health').status_code == 200 else exit(1)\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  mysql:
    image: mysql:8
    container_name: gemini-balance-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s # 每隔10秒检查一次
      timeout: 5s   # 每次检查的超时时间为5秒
      retries: 3    # 重试3次失败后标记为 unhealthy
      start_period: 30s # 容器启动后等待30秒再开始第一次健康检查